# Generated by Django 5.2.7 on 2025-10-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_window', models.IntegerField(default=220)),
                ('chosen_window', models.IntegerField(blank=True, null=True)),
                ('scan_cache_json', models.JSONField(blank=True, null=True)),
                ('scan_cached_at', models.DateTimeField(blank=True, null=True)),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_left', to='acoes.asset')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_right', to='acoes.asset')),
            ],
        ),
    ]
