# Generated by Django 5.2.7 on 2025-10-21 20:48

import django.core.validators
import django.db.models.deletion
import pairs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetricsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_window', models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(10)])),
                ('default_windows', models.CharField(default=pairs.models._default_windows_string, help_text='Lista de janelas (dias) separadas por virgula.', max_length=255)),
                ('adf_min', models.FloatField(default=95.0)),
                ('zscore_abs_min', models.FloatField(default=2.0)),
                ('beta_window', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracao de Métricas',
                'verbose_name_plural': 'Configuracoes de Métricas',
            },
        ),
    ]
