# Generated by Django 5.2.7 on 2025-10-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0002_usermetricsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetricsconfig',
            name='half_life_max',
            field=models.FloatField(default=5.0, help_text='Half-life maxima em dias. Use 0 para desativar o filtro.'),
        ),
    ]
