# Generated by Django 5.2.7 on 2025-10-13 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userasset',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userasset',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='logo_prefix',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker_yf',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='userasset',
            constraint=models.UniqueConstraint(fields=('user', 'asset'), name='unique_user_asset'),
        ),
    ]
