# Generated by Django 5.2.7 on 2025-11-04 20:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acoes', '0001_initial'),
        ('pairs', '0003_usermetricsconfig_half_life_max'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.PositiveIntegerField(default=220)),
                ('orientation', models.CharField(default='default', max_length=16)),
                ('source', models.CharField(default='manual', max_length=32)),
                ('sell_quantity', models.PositiveIntegerField()),
                ('buy_quantity', models.PositiveIntegerField(default=0)),
                ('lot_size', models.PositiveIntegerField(default=100)),
                ('lot_multiplier', models.PositiveIntegerField(default=1)),
                ('sell_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('buy_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('sell_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('buy_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('capital_allocated', models.DecimalField(decimal_places=2, max_digits=18)),
                ('entry_zscore', models.FloatField(blank=True, null=True)),
                ('trade_plan', models.JSONField(blank=True, null=True)),
                ('pair_metrics', models.JSONField(blank=True, null=True)),
                ('is_real', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Encerrada')], default='open', max_length=16)),
                ('operation_date', models.DateField(default=django.utils.timezone.now)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buy_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_buy', to='acoes.asset')),
                ('left_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_left', to='acoes.asset')),
                ('pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='pairs.pair')),
                ('right_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_right', to='acoes.asset')),
                ('sell_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_sell', to='acoes.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('open', 'Entrada'), ('current', 'Atual')], default='open', max_length=16)),
                ('reference_date', models.DateField(default=django.utils.timezone.now)),
                ('zscore', models.FloatField(blank=True, null=True)),
                ('half_life', models.FloatField(blank=True, null=True)),
                ('adf_pvalue', models.FloatField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('corr30', models.FloatField(blank=True, null=True)),
                ('corr60', models.FloatField(blank=True, null=True)),
                ('n_samples', models.IntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='operacoes.operation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['user', 'status'], name='operacoes_o_user_id_1d6cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['status', 'operation_date'], name='operacoes_o_status_1cc167_idx'),
        ),
        migrations.AddIndex(
            model_name='operationmetricsnapshot',
            index=models.Index(fields=['operation', 'snapshot_type'], name='operacoes_o_operati_52ef9d_idx'),
        ),
        migrations.AddIndex(
            model_name='operationmetricsnapshot',
            index=models.Index(fields=['snapshot_type', 'reference_date'], name='operacoes_o_snapsho_787658_idx'),
        ),
    ]
